### ISSUE TITLE
"osism complete" completion script - supposedly DOS line breaks

### ISSUE THREAD

**Issue by linwalth** [osism/python-osism#69]
When I try to use the script provided by osism complete i get this error when entering the shell after setting the script in /etc/bash_completion.d:

```
manager:~# sudo -i
-bash: /etc/bash_completion.d/osism: line 1: syntax error near unexpected token `$'\r''
'bash: /etc/bash_completion.d/osism: line 1: `_osism()
-bash: /etc/bash_completion.d/osism: line 1: syntax error near unexpected token `$'\r''
'bash: /etc/bash_completion.d/osism: line 1: `_osism()
```

**Comment by osfrickler** [comment]
This might happen if in order to generate your `/etc/bash_completion.d/osism` file you were redirecting the output of running the `osismclient` container. In that case, please use

```
INTERACTIVE=false osism complete > /etc/bash_completion.d/osism
```

**Comment by berendt** [comment]
It could make sense to add the generation of this file into the osism.services.manager role. This way we do not have to manually create this file.
