### ISSUE TITLE
osism client is not asking for ansible-vault password

### ISSUE THREAD

**Issue by grawert** [osism/python-osism#83]
When starting the osism client, it should ask for the ansible-vault password:
```
dragon@manager:~$ osism apply facts
[WARNING]: Error in vault password file loading (default): Invalid vault
password was provided from script (/opt/configuration/environments/.vault_pass)
ERROR! Invalid vault password was provided from script (/opt/configuration/environments/.vault_pass)
```

The help does not provide any guidance:
```
dragon@manager:~$ osism --help
usage: osism [--version] [-v | -q] [--log-file LOG_FILE] [-h] [--debug]

OSISM manager interface

optional arguments:
  --version             show program's version number and exit
  -v, --verbose         Increase verbosity of output. Can be repeated.
  -q, --quiet           Suppress output except warnings and errors.
  --log-file LOG_FILE
                        Specify a file to log output. Disabled by default.
  -h, --help            Show help message and exit.
  --debug               Show tracebacks on errors.

```

**Comment by berendt** [comment]
This is still a missing feature in python-osism. I am prioritizing the implementation of it to implement it next week if possible. Until then, please use the osism-* commands.

**Comment by berendt** [comment]
As a workaround change ``.vault_pass`` to a script with this content:

```
#!/usr/bin/env bash

cat /opt/configuration/secrets/vaultpass
```

The secret can be temporary stored in ``/opt/configuration/secrets/vaultpass``.

This will soon be changed into a script that can then access the Vault service.

**Comment by Nils98Ar** [comment]
@berendt @matfechner Is there a clean solution for osism apply now? We are still using the osism-* commands.

**Comment by berendt** [comment]
Not yet. We will resolved this in the next months by integrating the Hashicorp Vault service as backend for all secrets.

**Comment by Nils98Ar** [comment]
Thank you!
